// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/products": {
    params: {};
  };
  "/api/chat": {
    params: {};
  };
  "/api/search": {
    params: {};
  };
  "/api/orders": {
    params: {};
  };
  "/api/orders/test": {
    params: {};
  };
  "/api/orders/verify": {
    params: {};
  };
  "/api/orders/lookup": {
    params: {};
  };
  "/api/dashboard/metrics": {
    params: {};
  };
  "/api/dashboard/conversations": {
    params: {};
  };
  "/api/dashboard/conversations/:sessionId": {
    params: {
      "sessionId": string;
    };
  };
  "/api/dashboard/settings": {
    params: {};
  };
  "/api/dashboard/sync": {
    params: {};
  };
  "/api/dashboard/export": {
    params: {};
  };
  "/api/shop/settings": {
    params: {};
  };
  "/api/similar": {
    params: {};
  };
  "/webhooks/*": {
    params: {
      "*": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/dashboard/analytics": {
    params: {};
  };
  "/dashboard/conversations": {
    params: {};
  };
  "/dashboard/conversations/:sessionId": {
    params: {
      "sessionId": string;
    };
  };
  "/dashboard/test-chat": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/products" | "/api/chat" | "/api/search" | "/api/orders" | "/api/orders/test" | "/api/orders/verify" | "/api/orders/lookup" | "/api/dashboard/metrics" | "/api/dashboard/conversations" | "/api/dashboard/conversations/:sessionId" | "/api/dashboard/settings" | "/api/dashboard/sync" | "/api/dashboard/export" | "/api/shop/settings" | "/api/similar" | "/webhooks/*" | "/auth/login" | "/auth/*" | "/dashboard/analytics" | "/dashboard/conversations" | "/dashboard/conversations/:sessionId" | "/dashboard/test-chat" | "/dashboard/settings";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/api.products.tsx": {
    id: "routes/api.products";
    page: "/api/products";
  };
  "routes/api.chat.tsx": {
    id: "routes/api.chat";
    page: "/api/chat";
  };
  "routes/api.search.tsx": {
    id: "routes/api.search";
    page: "/api/search";
  };
  "routes/api.orders.tsx": {
    id: "routes/api.orders";
    page: "/api/orders";
  };
  "routes/api.orders.test.tsx": {
    id: "routes/api.orders.test";
    page: "/api/orders/test";
  };
  "routes/api.orders.verify.tsx": {
    id: "routes/api.orders.verify";
    page: "/api/orders/verify";
  };
  "routes/api.orders.lookup.tsx": {
    id: "routes/api.orders.lookup";
    page: "/api/orders/lookup";
  };
  "routes/api.dashboard.metrics.tsx": {
    id: "routes/api.dashboard.metrics";
    page: "/api/dashboard/metrics";
  };
  "routes/api.dashboard.conversations.$sessionId.tsx": {
    id: "api.dashboard.conversations.list";
    page: "/api/dashboard/conversations";
  } | {
    id: "api.dashboard.conversations.detail";
    page: "/api/dashboard/conversations/:sessionId";
  };
  "routes/api.dashboard.settings.tsx": {
    id: "routes/api.dashboard.settings";
    page: "/api/dashboard/settings";
  };
  "routes/api.dashboard.sync.tsx": {
    id: "routes/api.dashboard.sync";
    page: "/api/dashboard/sync";
  };
  "routes/api.dashboard.export.tsx": {
    id: "routes/api.dashboard.export";
    page: "/api/dashboard/export";
  };
  "routes/api.shop.settings.tsx": {
    id: "routes/api.shop.settings";
    page: "/api/shop/settings";
  };
  "routes/api.similar.tsx": {
    id: "routes/api.similar";
    page: "/api/similar";
  };
  "routes/webhooks.$.tsx": {
    id: "routes/webhooks.$";
    page: "/webhooks/*";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard/analytics" | "/dashboard/conversations" | "/dashboard/conversations/:sessionId" | "/dashboard/test-chat" | "/dashboard/settings";
  };
  "routes/dashboard.analytics.tsx": {
    id: "routes/dashboard.analytics";
    page: "/dashboard/analytics";
  };
  "routes/dashboard.conversations.tsx": {
    id: "routes/dashboard.conversations";
    page: "/dashboard/conversations";
  };
  "routes/dashboard.conversations.$sessionId.tsx": {
    id: "routes/dashboard.conversations.$sessionId";
    page: "/dashboard/conversations/:sessionId";
  };
  "routes/dashboard.test-chat.tsx": {
    id: "routes/dashboard.test-chat";
    page: "/dashboard/test-chat";
  };
  "routes/dashboard.settings.tsx": {
    id: "routes/dashboard.settings";
    page: "/dashboard/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/api.products": typeof import("./app/routes/api.products.tsx");
  "routes/api.chat": typeof import("./app/routes/api.chat.tsx");
  "routes/api.search": typeof import("./app/routes/api.search.tsx");
  "routes/api.orders": typeof import("./app/routes/api.orders.tsx");
  "routes/api.orders.test": typeof import("./app/routes/api.orders.test.tsx");
  "routes/api.orders.verify": typeof import("./app/routes/api.orders.verify.tsx");
  "routes/api.orders.lookup": typeof import("./app/routes/api.orders.lookup.tsx");
  "routes/api.dashboard.metrics": typeof import("./app/routes/api.dashboard.metrics.tsx");
  "api.dashboard.conversations.list": typeof import("./app/routes/api.dashboard.conversations.$sessionId.tsx");
  "api.dashboard.conversations.detail": typeof import("./app/routes/api.dashboard.conversations.$sessionId.tsx");
  "routes/api.dashboard.settings": typeof import("./app/routes/api.dashboard.settings.tsx");
  "routes/api.dashboard.sync": typeof import("./app/routes/api.dashboard.sync.tsx");
  "routes/api.dashboard.export": typeof import("./app/routes/api.dashboard.export.tsx");
  "routes/api.shop.settings": typeof import("./app/routes/api.shop.settings.tsx");
  "routes/api.similar": typeof import("./app/routes/api.similar.tsx");
  "routes/webhooks.$": typeof import("./app/routes/webhooks.$.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard.analytics": typeof import("./app/routes/dashboard.analytics.tsx");
  "routes/dashboard.conversations": typeof import("./app/routes/dashboard.conversations.tsx");
  "routes/dashboard.conversations.$sessionId": typeof import("./app/routes/dashboard.conversations.$sessionId.tsx");
  "routes/dashboard.test-chat": typeof import("./app/routes/dashboard.test-chat.tsx");
  "routes/dashboard.settings": typeof import("./app/routes/dashboard.settings.tsx");
};